### ISSUE TITLE
unknown headers of `final_result.csv`

### ISSUE THREAD

**Issue by chyanju** [dhkim16/VisQA-release#2]
Hi! I'm very interested in this project and am setting up the environments. I managed to get Stage1 and Stage2 running, where for Stage2 the server would return the json that is similar to the following:
```
{"sessionId": "A17d1459d3905d0a8cb27fd9750c65ec74360a6f4f28c8ca22aa673af1594", "questionId": "Q01cd2b120e531a16339954fd43a1830683a5095a556008af97f955abd76c", "visQuery": "when apple price starts to be larger than IBM ?", "systemAnswer": "90", "formula": "(max (argmax (number 1) (number 1) ((reverse fb:cell.cell.number) ((reverse fb:row.row.age) (fb:type.object.type fb:type.row))) (reverse (lambda x (count (fb:row.row.age (fb:cell.cell.number (var x))))))))"}
```

And for Stage3, as the `GenerateExplanation.py` seems to require the output from Stage2 (according to the pipeline in the paper), which I figured should be stored in `final_result.csv`: 
[https://github.com/dhkim16/VisQA-release/blob/4967bfde2d232450c5c6ef634bd9aa755b7bd236/code/GenerateExplanation.py#L463](https://github.com/dhkim16/VisQA-release/blob/4967bfde2d232450c5c6ef634bd9aa755b7bd236/code/GenerateExplanation.py#L463)
While the json returned from Stage2 only has 5 columns/keys, and obviously the `GenerateExplanation.py` is trying to read the 9th column of that csv:
https://github.com/dhkim16/VisQA-release/blob/4967bfde2d232450c5c6ef634bd9aa755b7bd236/code/GenerateExplanation.py#L472

Would you mind sharing a sample `final_result.csv`? Not sure about what extra headers are needed and how I should order them. Thanks!

**Comment by dhkim16** [comment]
Thank you for your interest in the project.
The output from Stage 2 is indeed stored into 'final_result.csv'.
If I remember correctly, Stage 3 only uses the 'formula' from Stage 2 and you can simply set the column '8' (9th column) to be the formula or simply change line 472 to refer to whichever column you save the data into.

For your reference, this was the first two rows of final_result.csv that I input into Stage 3:
```
"questionId","question","isVisual","dataset","visualizationName","spec","answer","visQuestion","systemFormula","systemAnswer","isCorrect"
"Q-Q0d9203b5daa57e4c9b3dc89464eb908a243caceb9d7f584dcc54bd033262","Which age has the highest population number?","false","vega-lite-example-gallery","bar_aggregate","bar_aggregate.json","35","Which age has the highest population number ?","(argmax (number 1) (number 1) ((reverse fb:row.row.age) (fb:type.object.type fb:type.row)) (reverse (lambda x ((reverse fb:cell.cell.number) ((reverse fb:row.row.age) (fb:row.row.age (var x)))))))","90","false"
```

Let me know if you run into any other issue.

**Comment by chyanju** [comment]
Great! Thank you!
